# Generated by Django 5.0.3 on 2024-06-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEmploymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_reference', models.CharField(max_length=200)),
                ('Period', models.FloatField()),
                ('Data_value', models.CharField(max_length=100)),
                ('Suppressed', models.CharField(max_length=100, null=True)),
                ('STATUS', models.CharField(max_length=100)),
                ('UNITS', models.CharField(max_length=100)),
                ('Magnitude', models.IntegerField()),
                ('Subject', models.CharField(max_length=100)),
                ('Group', models.CharField(max_length=100)),
                ('Series_title_1', models.CharField(max_length=100)),
                ('Series_title_2', models.CharField(max_length=300)),
                ('Series_title_3', models.CharField(max_length=100)),
                ('Series_title_4', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
